name: docx_viewer_plus
description: Flutter DOCX Viewer & Editor for opening, reading, editing, and saving Word (.docx) files across Android, iOS, and macOS.
version: 1.0.0
homepage: https://github.com/muslimbinsohail/docx_viewer_plus
repository: https://github.com/muslimbinsohail/docx_viewer_plus

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  # UI
  # File handling
  path_provider: ^2.1.5
  # DOCX parsing (ZIP + XML)
  archive: ^4.0.9
  xml: ^6.5.0
  # WebView for rendering + editing
  webview_flutter: ^4.13.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true
